### ISSUE TITLE
KeyError: Swapped

### ISSUE THREAD

**Issue by ibaguio** [beanbaginc/django-evolution#1]
When trying to mutate the database with the following:

```
#----- Evolution for dashboard
from django_evolution.mutations import AddField
from django.db import models


MUTATIONS = [
    AddField('MyUser', 'is_manager', models.BooleanField, initial=False),
    AddField('MyUser', 'manager', models.ForeignKey, null=True, related_model=u'dashboard.MyUser')
]
#----------------------
#----- Evolution for project
from django_evolution.mutations import AddField, DeleteField
from django.db import models


MUTATIONS = [
    AddField('LandingPage', 'name', models.CharField, initial=u'My Page', max_length=64),
    AddField('LandingPage', 'owner', models.ManyToManyField, related_model=u'dashboard.MyUser'),
    AddField('AccessPoint', 'lp', models.ForeignKey, null=True, related_model=u'project.LandingPage'),
    DeleteField('LandingPage', 'ap')
]
```

i get the following error:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django_evolution/management/commands/evolve.py", line 60, in handle
    self.evolve(*app_labels, **options)
  File "/usr/local/lib/python2.7/dist-packages/django_evolution/management/commands/evolve.py", line 140, in evolve
    database))
  File "/usr/local/lib/python2.7/dist-packages/django_evolution/mutations.py", line 424, in mutate
    return self.add_m2m_table(app_label, proj_sig, database)
  File "/usr/local/lib/python2.7/dist-packages/django_evolution/mutations.py", line 473, in add_m2m_table
    sql_statements = evolver.add_m2m_table(model, field)
  File "/usr/local/lib/python2.7/dist-packages/django_evolution/db/common.py", line 86, in add_m2m_table
    sql, references = creation.sql_create_model(f.rel.through, style)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/creation.py", line 46, in sql_create_model
    if not opts.managed or opts.proxy or opts.swapped:
  File "/usr/local/lib/python2.7/dist-packages/django_evolution/mutations.py", line 164, in __getattr__
    return self.meta[name]
KeyError: 'swapped'
```

django-evolution version 1.6.2

**Comment by chipx86** [comment]
Fixed in Django Evolution 2.0 (releasing this week).
